// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfvqgnfpyvcmiumpbssd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdnFnbmZweXZjbWl1bXBic3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDk2MjgsImV4cCI6MjA1OTU4NTYyOH0.vLBom-GcCnGhDEAED4M4fB8vXRM0pdhgMzQAPKqOqqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);